# if enabled, players will need itemswitch.use
# for the plugin to work for them
requirePermission: false

# below are default settings for players
# these can be changed with /itemswitch toggle [event]
blockPlace: true
itemBreak: true
itemConsume: true
bucketEmpty: true
dropItem: true