name: ItemSwitch
version: '2025.6.1.0'
main: site.remlit.blueb.itemswitch.ItemSwitch
api-version: '1.20'
load: STARTUP
authors: [ blueb ]

permissions:
  itemswitch.use:
    description: "Allow players to use the plugin"
    default: notop